# -*- coding: utf-8 -*-
############################################################
#
# Autogenerated by the KBase type compiler -
# any changes made here will be overwritten
#
############################################################

from __future__ import print_function
# the following is a hack to get the baseclient to import whether we're in a
# package or not. This makes pep8 unhappy hence the annotations.
try:
    # baseclient and this client are in a package
    from .baseclient import BaseClient as _BaseClient  # @UnusedImport
except:
    # no they aren't
    from baseclient import BaseClient as _BaseClient  # @Reimport


class GenericsUtil(object):

    def __init__(
            self, url=None, timeout=30 * 60, user_id=None,
            password=None, token=None, ignore_authrc=False,
            trust_all_ssl_certificates=False,
            auth_svc='https://kbase.us/services/authorization/Sessions/Login'):
        if url is None:
            raise ValueError('A url is required')
        self._service_ver = None
        self._client = _BaseClient(
            url, timeout=timeout, user_id=user_id, password=password,
            token=token, ignore_authrc=ignore_authrc,
            trust_all_ssl_certificates=trust_all_ssl_certificates,
            auth_svc=auth_svc)

    def import_csv(self, params, context=None):
        """
        :param params: instance of type "ImportCSVParams" (Import a CSV file
           into a NDArray or HNDArray) -> structure: parameter "file" of type
           "File" -> structure: parameter "path" of String, parameter
           "shock_id" of String, parameter "workspace_name" of String,
           parameter "object_name" of String, parameter "object_type" of
           String, parameter "metadata" of type "usermeta" -> mapping from
           String to String
        :returns: instance of type "ImportResult" -> structure: parameter
           "object_ref" of String
        """
        return self._client.call_method(
            'GenericsUtil.import_csv',
            [params], self._service_ver, context)

    def import_obo(self, params, context=None):
        """
        :param params: instance of type "ImportOBOParams" (Import an OBO file
           into an OntologyDictionary) -> structure: parameter "file" of type
           "File" -> structure: parameter "path" of String, parameter
           "shock_id" of String, parameter "workspace_name" of String,
           parameter "object_name" of String, parameter "metadata" of type
           "usermeta" -> mapping from String to String
        :returns: instance of type "ImportResult" -> structure: parameter
           "object_ref" of String
        """
        return self._client.call_method(
            'GenericsUtil.import_obo',
            [params], self._service_ver, context)

    def export_csv(self, params, context=None):
        """
        :param params: instance of type "ExportParams" (Exporter for generic
           objects as CSV files) -> structure: parameter "input_ref" of String
        :returns: instance of type "ExportResult" -> structure: parameter
           "shock_id" of String
        """
        return self._client.call_method(
            'GenericsUtil.export_csv',
            [params], self._service_ver, context)

    def status(self, context=None):
        return self._client.call_method('GenericsUtil.status',
                                        [], self._service_ver, context)
